# =================================================================
#
# Authors: Tom Kralidis <tomkralidis@gmail.com>
#
# Copyright (c) 2020 Tom Kralidis
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following
# conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# =================================================================

server:
    bind:
        host: 0.0.0.0
        port: 5000
    url: http://localhost:5000
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    gzip: false
    languages:
        # First language is the default language
        - "no"
    cors: true
    pretty_print: true
    limit: 10
    # templates:
      # path: /path/to/Jinja2/templates
      # static: /path/to/static/folder # css/js/img
    map:
        url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
        attribution: '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'
#    manager:
#        name: TinyDB
#        connection: /tmp/pygeoapi-process-manager.db
#        output_dir: /tmp/
    # ogc_schemas_location: /opt/schemas.opengis.net

logging:
    level: INFO
    # logfile: /tmp/pygeoapi.log

metadata:
    identification:
        title:
            "no": OGC API-tjenester - Kartverket
        description:
            "no": OGC API er en ny generasjon standarder fra Open Geospatial Consortium. På denne serveren tilbys testimplementasjoner av Coverages- og Processes-spesifikasjonene.
        keywords:
            "no":
                - Geodata
                - API
                - OGC
        keywords_type: theme
        terms_of_service: https://creativecommons.org/licenses/by/4.0/
        url: https://example.org
    license:
        name: CC-BY 4.0 license
        url: https://creativecommons.org/licenses/by/4.0/
    provider:
        name: Kartverket
        url: https://kartverket.no
    contact:
        name: Lastname, Firstname
        position: Position Title
        address: Mailing Address
        city: City
        stateorprovince: Administrative Area
        postalcode: Zip or Postal Code
        country: Country
        phone: +xx-xxx-xxx-xxxx
        fax: +xx-xxx-xxx-xxxx
        email: tjenestedrift@kartverket.no
        url: Contact URL
        hours: Mo-Fr 08:00-17:00
        instructions: During hours of service. Off on weekends.
        role: pointOfContact

resources:   
    dtm-10-terrengmodell:
        type: collection
        title: DTM 10 Terrengmodell (UTM32)
        description: Digital terrengmodell over fastlands-Norge med høyder i et rutenett på 10 x 10 meter. Terrengmodellen er en rutenettsmodell med oppløsning (rutenettstørrelse) på 10 x 10 meter.
        keywords:
            - DTM
            - Høydemodell
            - Terrengmodell
            - Digital terrengmodell
            - DEM
            - Høyde
        extents:
            spatial:
                bbox: [8.99, 58.63, 9.87, 59.08]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
        links:
            - type: text/html
              rel: canonical
              title: Information
              href: https://kartkatalog.geonorge.no/metadata/dtm-10-terrengmodell-utm32/fd851873-f363-46f9-9fc6-bb1b403575df
              hreflang: nb-NO
        providers:
            - type: coverage
              name: rasterio
              data: tests/data/dtm-10-terrengmodell/6505_3_10m_z32.cog.tif
              format:
                  name: GTiff
                  mimetype: application/geotiff

    dybdedata-terrengmodell-50-meters-grid-rogaland:
        type: collection
        title: Dybdedata - terrengmodell 50 meters grid for Rogaland
        description: Grov terrengmodell i 50 m oppløsning som viser terrengvariasjon på havbunnen for sjø- og havområder utenfor Rogaland. Terrengmodellen har blitt generert ved bruk av interpolering og har derfor varierende kvalitet med hensyn til pålitelighet i posisjon og dybde.
        keywords:
            - Sjø
            - Dybde
            - Dybdedata
            - Terrengmodell
            - Grid
            - 3D
            - Skyggerelieff
            - Hav
            - Sjødata
        extents:
            spatial:
                bbox: [3.35, 59.94, 6.49, 58.03]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
        links:
            - type: text/html
              rel: canonical
              title: Information
              href: https://kartkatalog.geonorge.no/metadata/dybdedata-terrengmodeller-50-meters-grid-landsdekkende/bbd687d0-d34f-4d95-9e60-27e330e0f76e
              hreflang: nb-NO
        providers:
            - type: coverage
              name: rasterio
              data: tests/data/dybdedata-terrengmodeller-50-meters-grid-rogaland/B0608_grid50_utm33.cog.tif
              format:
                  name: GTiff
                  mimetype: application/geotiff

    fullstendighetsdekning:
        type: process
        processor:
            name: Fullstendighetsdekning

